# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome
# Comment to be posted to on first time issues

newIssueWelcomeComment: >
  Hello there!ğŸ‘‹ Welcome to the project!ğŸš€âš¡
  
  
  Thank you and congratsğŸ‰for opening your very first issue in this project.ğŸ™Œ Aiden is a web app utilising tensorflow.js, browser-based Machine Learning library,
  to enable accessible physiotherapy for the Visually Impaired and other people as well - talking through exercises by responding to users' postures in real-time.
  
  Please wait while we get back to you on this issue.
  
  Feel free to join our [Discord Community](https://discord.gg/ZHDd59yE).ğŸ’– We have different channels for active discussions.âœ¨ Hope you have a great time there!ğŸ˜„

 
# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome
# Comment to be posted to on PRs from first time contributors in your repository

newPRWelcomeComment: >
  Hello there!ğŸ‘‹ Welcome to the project!ğŸ’–
  
  
  Thank you and congratsğŸ‰ for opening your first pull request. âœ¨ Aiden is a web app utilising tensorflow.js, browser-based Machine Learning library,
  to enable accessible physiotherapy for the Visually Impaired and other people as well - talking through exercises by responding to users' postures in real-time.
  
  The maintainer will review your PR soon.
  
  Feel free to join our [Discord Community](https://discord.gg/ZHDd59yE).ğŸ’– We have different channels for active discussions.âœ¨ Hope you have a great time there!ğŸ˜„

  
# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge
# Comment to be posted to on pull requests merged by a first time user

firstPRMergeComment: >
  Congrats on merging your first pull request! ğŸ‰ All the best for your amazing open source journey ahead ğŸš€.
